apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/monitoring
    server: 172.31.32.46
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage