apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment
  namespace: my-test-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod-label
  template:
    metadata:
      labels:
        app: nginx-pod-label
      namespace: my-test-nginx
    spec:
      containers:
        - image: nginx
          name: my-nginx-pod
          ports:
            - containerPort: 80
              name: tcp
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: my-test-nginx
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-pod-label
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
  namespace: my-test-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.domaincuatui.space
      http:
        paths:
          - backend:
              service:
                name: nginx-test-service
                port:
                  number: 8080
            path: /
            pathType: Prefix