apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data
    server: 172.31.32.46
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage