architecture: replication

image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 7.4.1-debian-12-r0
  pullPolicy: Always
  
auth:
  enabled: true
  password: "devopseduvn"

master:
  persistence:
    enabled: true
    existingClaim: redis-pvc
    size: 3Gi

replica:
  replicaCount: 3
  persistence:
    enabled: true
    existingClaim: redis-pvc
    size: 3Gi

# đảm bảo khả năng failover
sentinel:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis-sentinel
    tag: 7.4.1-debian-12-r0
    pullPolicy: Always
  enabled: true
  replicas: 3
