architecture: replication

auth:
  enabled: true
  password: "devopseduvn"

master:
  persistence:
    enabled: true
    existingClaim: redis-pvc
    size: 3Gi

replica:
  replicaCount: 3
  persistence:
    enabled: true
    existingClaim: redis-pvc
    size: 3Gi

# đảm bảo khả năng failover
sentinel:
  enabled: true
  replicas: 3
